Assemble : main firstPass error checkOpration directive storeFirst  opration dataOpration dataTObinary
	gcc -Wall -pedantic -ansi main.o firstPass.o handleError.o checkOpration.o directive.o storeFirstPess.o oprationWork.o  dataOpcode.o dataTObinary.o -o run
main:    main.c symbol.h
	gcc -c -Wall -pedantic -ansi main.c -o main.o
firstPass:   symbol.c symbol.h
	gcc -c -Wall -pedantic -ansi symbol.c -o firstPass.o
error:   handleError.c symbol.h
	gcc -c -Wall -pedantic -ansi handleError.c -o handleError.o
checkOpration:   checkOpration.c symbol.h
	gcc -c -Wall -pedantic -ansi checkOpration.c -o checkOpration.o
directive:   directive.c symbol.h
	gcc -c -Wall -pedantic -ansi directive.c -o directive.o
storeFirst:  storeFirstPess.c symbol.h
	gcc -c -Wall -pedantic -ansi storeFirstPess.c -o storeFirstPess.o
opration:   oprationWork.c symbol.h
	gcc -c -Wall -pedantic -ansi oprationWork.c -o oprationWork.o
dataOpration:   dataOpcode.c symbol.h
	gcc -c -Wall -pedantic -ansi dataOpcode.c -o dataOpcode.o
dataTObinary:   dataTObinary.c symbol.h
	gcc -c -Wall -pedantic -ansi dataTObinary.c -o dataTObinary.o



